parameters:
#    task_test.example.class: Task\TestBundle\Example

services:
#    task_test.example:
#        class: %task_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
